# This is a basic workflow to help you get started with Actions

name: Check for prettier

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Format prettier
        run: npm run format

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Format code with Prettier"
